version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: frazao
      POSTGRES_PASSWORD: frazao
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
       - ./data-postgres/:/var/lib/postgres
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
networks:
  default:
    driver: bridge
    name: postgres